<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mmtr">

    <xacro:include filename="inertial_macros.xacro" />
    <xacro:property name="wheel_mass" value="0.2" />
    <xacro:property name="chassis_mass" value="0.5" />
    <xacro:property name="wheel_length" value="0.01" />
    <xacro:property name="wheel_radius" value="0.03" />
    <xacro:property name="chassis_length" value="0.03" />
    <xacro:property name="chassis_width" value="0.05" />
    <xacro:property name="chassis_height" value="0.1" />


    <material name="orange">
        <color rgba="1 0.3 0.1" />
    </material>

    <material name="blue">
        <color rgba="0 0 1" />
    </material>

    <material name="green">
        <color rgba="0 1 0" />
    </material>

    <link name="base_footprint" />

    <joint name="chassis_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="base_link">
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}"
            z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="orange" />
        </visual>

        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <link name="right_wheel_link">
        <xacro:inertial_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_length}">
            <origin />
        </xacro:inertial_cylinder>

        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
        </collision>
    </link>

        <gazebo reference="right_wheel_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <link name="left_wheel_link">
        <xacro:inertial_cylinder mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_length}">
            <origin />
        </xacro:inertial_cylinder>

        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Red</material>
    </gazebo>
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="${chassis_length/2} 0.031 0.0" rpy="${pi/2} 0.0 0.0" />
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <axis xyz="0.0 0.0 1" />
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0" />
    </joint>


    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="${chassis_length/2} -0.031 0.0" rpy="${pi/2} 0.0 0.0" />
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <axis xyz="0.0 0.0 1" />
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0" />
    </joint>
</robot>
    